project:
  type: website

website:
  title: "Smartwatch analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: source.qmd
        text: Source

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


